server:
  port: 9090

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/bootdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: springuser
    password: mysql
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
    show-sql: true
    
  thymeleaf:
    cache: false